<?php

defined( 'ABSPATH' ) || exit;

final class SCHA_Provider_Local implements SCHA_Provider_Interface {
    public function key(): string {
        return 'local';
    }

    public function is_available(): bool {
        return true;
    }

    public function generate( array $request ): array|WP_Error {
        $sources = $request['sources'] ?? array();
        if ( empty( $sources ) ) {
            return new WP_Error( 'scha_evidence_insufficient', __( 'The approved corpus does not contain enough accessible evidence to answer this question.', SCHA_TEXT_DOMAIN ) );
        }

        $parts = array();
        foreach ( array_slice( $sources, 0, 3 ) as $index => $source ) {
            $text = trim( wp_strip_all_tags( (string) $source['content'] ) );
            $sentences = preg_split( '/(?<=[.!?۔؟])\s+/u', $text ) ?: array( $text );
            $excerpt = trim( implode( ' ', array_slice( array_filter( $sentences ), 0, 2 ) ) );
            if ( '' !== $excerpt ) {
                $excerpt = function_exists( 'mb_substr' ) ? mb_substr( $excerpt, 0, 650 ) : substr( $excerpt, 0, 650 );
                $parts[] = $excerpt . ' [S' . ( $index + 1 ) . ']';
            }
        }
        if ( empty( $parts ) ) {
            return new WP_Error( 'scha_evidence_insufficient', __( 'The approved corpus does not contain enough accessible evidence to answer this question.', SCHA_TEXT_DOMAIN ) );
        }

        $answer = __( 'The approved educational sources contain the following relevant points:', SCHA_TEXT_DOMAIN ) . "\n\n" . implode( "\n\n", $parts ) . "\n\n" . __( 'This is educational source retrieval, not an individual diagnosis, prescription, potency, dosage, or emergency service.', SCHA_TEXT_DOMAIN );
        return array(
            'answer'       => $answer,
            'provider'     => 'local',
            'model'        => 'extractive-lexical-v1',
            'response_id'  => wp_generate_uuid4(),
            'input_tokens' => SCHA_Usage_Ledger::estimate_tokens( (string) ( $request['prompt'] ?? '' ) ),
            'output_tokens'=> SCHA_Usage_Ledger::estimate_tokens( $answer ),
            'cost_micros'  => 0,
            'disclosure'   => __( 'Generated by the local evidence-extractive fallback.', SCHA_TEXT_DOMAIN ),
        );
    }
}
